// ===== 土木专业英语单词库（每日50个轮换）=====
window.DB.words = [
 {en:"bridge",cn:"n. 桥梁",s:"The bridge spans the Yangtze River.",sc:"这座桥横跨长江。"},
 {en:"beam",cn:"n. 梁",s:"The main beam carries the traffic load.",sc:"主梁承受交通荷载。"},
 {en:"girder",cn:"n. 主梁；大梁",s:"Steel girders were erected last week.",sc:"钢主梁上周完成架设。"},
 {en:"column",cn:"n. 柱",s:"Each column supports the deck above.",sc:"每根柱子支撑上方桥面。"},
 {en:"pier",cn:"n. 桥墩",s:"The pier stands in the river.",sc:"桥墩矗立在河中。"},
 {en:"abutment",cn:"n. 桥台",s:"The abutment connects the bridge to the bank.",sc:"桥台把桥与河岸连接起来。"},
 {en:"foundation",cn:"n. 基础",s:"A pile foundation was adopted here.",sc:"这里采用了桩基础。"},
 {en:"pile",cn:"n. 桩",s:"Bored piles reach the bedrock.",sc:"钻孔桩深达基岩。"},
 {en:"deck",cn:"n. 桥面",s:"The deck is paved with asphalt.",sc:"桥面铺筑了沥青。"},
 {en:"span",cn:"n./v. 跨径；跨越",s:"The main span is 1,092 meters.",sc:"主跨为1092米。"},
 {en:"load",cn:"n. 荷载",s:"Dead load and live load are considered.",sc:"设计需考虑恒载与活载。"},
 {en:"stress",cn:"n. 应力",s:"The stress must not exceed the limit.",sc:"应力不得超过限值。"},
 {en:"strain",cn:"n. 应变",s:"Strain gauges monitor the girder.",sc:"应变片监测主梁。"},
 {en:"concrete",cn:"n. 混凝土",s:"Concrete is strong in compression.",sc:"混凝土抗压能力强。"},
 {en:"reinforcement",cn:"n. 钢筋；加固",s:"Reinforcement resists tensile forces.",sc:"钢筋抵抗拉力。"},
 {en:"prestressed",cn:"adj. 预应力的",s:"Prestressed concrete allows longer spans.",sc:"预应力混凝土可实现更大跨径。"},
 {en:"cable",cn:"n. 缆索；拉索",s:"The cables support the bridge deck.",sc:"缆索支撑着桥面。"},
 {en:"suspension bridge",cn:"n. 悬索桥",s:"A suspension bridge suits very long spans.",sc:"悬索桥适用于超大跨径。"},
 {en:"cable-stayed bridge",cn:"n. 斜拉桥",s:"The cable-stayed bridge has two tall pylons.",sc:"这座斜拉桥有两座高塔。"},
 {en:"arch",cn:"n. 拱",s:"The arch transfers load in compression.",sc:"拱以受压方式传递荷载。"},
 {en:"truss",cn:"n. 桁架",s:"The truss consists of triangular units.",sc:"桁架由三角形单元组成。"},
 {en:"pylon",cn:"n. 桥塔",s:"The pylon rises 300 meters.",sc:"桥塔高达300米。"},
 {en:"anchorage",cn:"n. 锚碇",s:"The anchorage resists the cable tension.",sc:"锚碇承受主缆拉力。"},
 {en:"bearing",cn:"n. 支座",s:"Rubber bearings allow small movements.",sc:"橡胶支座允许微小位移。"},
 {en:"expansion joint",cn:"n. 伸缩缝",s:"Expansion joints absorb thermal movement.",sc:"伸缩缝吸收温度变形。"},
 {en:"bending moment",cn:"n. 弯矩",s:"The bending moment peaks at midspan.",sc:"弯矩在跨中达到最大。"},
 {en:"shear force",cn:"n. 剪力",s:"Shear force is largest near supports.",sc:"剪力在支点附近最大。"},
 {en:"deflection",cn:"n. 挠度",s:"The deflection is within the allowable value.",sc:"挠度在容许值以内。"},
 {en:"fatigue",cn:"n. 疲劳",s:"Fatigue cracks were found in the steel deck.",sc:"钢桥面发现疲劳裂缝。"},
 {en:"corrosion",cn:"n. 腐蚀",s:"Corrosion protection extends service life.",sc:"防腐措施可延长使用寿命。"},
 {en:"durability",cn:"n. 耐久性",s:"Durability design targets 100 years.",sc:"耐久性设计目标为100年。"},
 {en:"seismic",cn:"adj. 地震的",s:"Seismic design prevents collapse.",sc:"抗震设计防止倒塌。"},
 {en:"vibration",cn:"n. 振动",s:"Wind-induced vibration was observed.",sc:"观察到风致振动。"},
 {en:"aerodynamic",cn:"adj. 空气动力的",s:"Aerodynamic stability was verified in a wind tunnel.",sc:"通过风洞验证了气动稳定性。"},
 {en:"construction",cn:"n. 施工；建造",s:"Construction began in 2023.",sc:"工程于2023年开工。"},
 {en:"cantilever",cn:"n. 悬臂",s:"The cantilever method needs no scaffolding below.",sc:"悬臂法无需桥下支架。"},
 {en:"formwork",cn:"n. 模板",s:"Formwork shapes the fresh concrete.",sc:"模板塑造新浇混凝土的形状。"},
 {en:"scaffolding",cn:"n. 脚手架",s:"Scaffolding was removed after curing.",sc:"养护完成后拆除脚手架。"},
 {en:"curing",cn:"n. 养护",s:"Proper curing prevents cracking.",sc:"充分养护可防止开裂。"},
 {en:"grouting",cn:"n. 压浆；灌浆",s:"Grouting protects the tendons.",sc:"压浆保护预应力筋。"},
 {en:"survey",cn:"n./v. 测量",s:"A precise survey guided the closure.",sc:"精密测量指导合龙。"},
 {en:"alignment",cn:"n. 线形；轴线",s:"The alignment follows the valley.",sc:"线路沿山谷布设。"},
 {en:"specification",cn:"n. 规范；技术要求",s:"Work must follow the design specification.",sc:"施工必须遵循设计规范。"},
 {en:"tender",cn:"n. 投标；标书",s:"Three firms submitted tenders.",sc:"三家公司提交了标书。"},
 {en:"budget",cn:"n. 预算",s:"The project stayed within budget.",sc:"项目未超出预算。"},
 {en:"cost estimate",cn:"n. 造价估算",s:"The cost estimate covers materials and labor.",sc:"造价估算包含材料与人工。"},
 {en:"quantity",cn:"n. 工程量",s:"Bill of quantities lists all works.",sc:"工程量清单列出全部工作。"},
 {en:"supervision",cn:"n. 监理；监督",s:"Site supervision ensures quality.",sc:"现场监理保证质量。"},
 {en:"maintenance",cn:"n. 养护；维修",s:"Regular maintenance keeps the bridge safe.",sc:"定期养护保障桥梁安全。"},
 {en:"inspection",cn:"n. 检测；检查",s:"Annual inspection found no defects.",sc:"年度检测未发现缺陷。"}
];
