// ===== 保研推免资讯库 =====
// 院校范围：综合/学科排名高于西南交通大学，及西南交通大学本体（985/211）
// 专业方向：土木工程 / 交通运输工程 / 经管类（含工程造价背景友好方向）
// 不限制条数，持续扩充；点击链接直达各校研究生招生网核实
window.DB.baoyan = [
 {school:"清华大学",lv:"985",major:"土木工程",type:"夏令营",title:"土木工程系优秀大学生夏令营招生通知",time:"5月-6月报名，7月初营期",req:"本科前10%，六级≥480，土木/交通相关专业",form:"学术报告+专业面试+英语口语面试",link:"https://yz.tsinghua.edu.cn"},
 {school:"清华大学",lv:"985",major:"土木工程（直博）",type:"直博",title:"土木水利学院桥梁与隧道方向直博生招生动态",time:"9-10月申请-考核",req:"科研潜力突出，有论文/竞赛者优先",form:"导师推荐+学院综合考核",link:"https://yz.tsinghua.edu.cn"},
 {school:"北京大学",lv:"985",major:"工程管理/力学",type:"预推免",title:"工学院接收推荐免试研究生（力学与工程管理方向）",time:"9月中旬",req:"推免资格，前20%，理工背景",form:"综合面试+英语",link:"https://admission.pku.edu.cn"},
 {school:"复旦大学",lv:"985",major:"经管类",type:"夏令营",title:"管理学院金融与工程管理夏令营（工科跨保友好）",time:"5-6月报名",req:"前15%，数学基础好",form:"笔试（数学+经管）+群面",link:"https://gsao.fudan.edu.cn"},
 {school:"上海交通大学",lv:"985",major:"土木水利",type:"夏令营",title:"船舶海洋与建筑工程学院优秀大学生夏令营",time:"5月底报名，7月营期",req:"前15%，大跨结构与桥隧方向",form:"笔试+面试+英语口试",link:"https://yjs.sjtu.edu.cn"},
 {school:"同济大学",lv:"985",major:"土木工程（桥梁方向）",type:"夏令营",title:"土木工程学院桥梁工程系全国优秀学生夏令营",time:"5月下旬报名，7月营期",req:"985/211本科，排名前15%，桥梁方向兴趣浓厚",form:"笔试（材料力学+结构力学）+综合面试",link:"https://yz.tongji.edu.cn"},
 {school:"同济大学",lv:"985",major:"桥梁工程",type:"导师动态",title:"桥梁健康监测与智能养护课题组发布招生说明",time:"预推免前均可联系",req:"对智能建造、数字孪生感兴趣者优先",form:"提交成绩单+个人陈述",link:"https://bridge.tongji.edu.cn"},
 {school:"同济大学",lv:"985",major:"交通运输",type:"预推免",title:"交通运输工程学院预推免接收通知",time:"9月上旬",req:"推免资格，前20%",form:"专业面试+英语自我介绍",link:"https://yz.tongji.edu.cn"},
 {school:"东南大学",lv:"985",major:"土木工程/桥隧",type:"预推免",title:"交通学院桥梁与隧道工程预推免接收通知",time:"9月上旬报名",req:"取得推免资格，专业前20%，六级≥425",form:"专业面试+英语自我介绍+文献翻译",link:"https://yzb.seu.edu.cn"},
 {school:"东南大学",lv:"985",major:"桥梁与隧道",type:"导师动态",title:"桥梁系教授团队（大跨桥梁健康监测）招收推免生2-3名",time:"常年接受邮件联系",req:"欢迎有编程基础（Python/MATLAB）的同学",form:"邮件简历+线上交流",link:"https://civil.seu.edu.cn"},
 {school:"浙江大学",lv:"985",major:"土木水利",type:"直博",title:"建筑工程学院直博生（桥隧方向）招生动态",time:"9-10月申请",req:"科研潜力突出，有竞赛/论文者优先",form:"导师推荐+学院综合考核",link:"https://grs.zju.edu.cn"},
 {school:"浙江大学",lv:"985",major:"工程管理",type:"夏令营",title:"工程师学院工程管理（MEM）优秀大学生夏令营",time:"6月报名",req:"前25%，工科背景优先",form:"面试为主+英语问答",link:"https://grs.zju.edu.cn"},
 {school:"哈尔滨工业大学",lv:"985",major:"土木/交通",type:"夏令营",title:"交通科学与工程学院优秀学子夏令营",time:"6月报名，7月中旬营期",req:"前15%，可跨专业（造价/管理背景可申请）",form:"学科考核+导师组面试",link:"http://yzb.hit.edu.cn"},
 {school:"哈尔滨工业大学",lv:"985",major:"桥梁与隧道",type:"预推免",title:"土木工程学院桥隧方向预推免通知",time:"9月",req:"推免资格，前20%，寒区桥梁特色",form:"专业面试+文献翻译",link:"http://yzb.hit.edu.cn"},
 {school:"天津大学",lv:"985",major:"土木工程",type:"夏令营",title:"建筑工程学院全国优秀大学生夏令营",time:"5月底报名",req:"前15%，大跨桥梁与钢结构方向",form:"笔试+面试+参观实验室",link:"http://yzb.tju.edu.cn"},
 {school:"天津大学",lv:"985",major:"经管类",type:"预推免",title:"管理与经济学部预推免（工程造价背景契合）",time:"9月中旬",req:"前20%，管科/工程管理方向",form:"综合面试+英语听说",link:"http://yzb.tju.edu.cn"},
 {school:"大连理工大学",lv:"985",major:"土木水利",type:"预推免",title:"建设工程学部接收推免生（含桥隧）预报名",time:"9月上旬",req:"推免资格，桥梁抗震方向有名额",form:"综合面试+专业英语翻译",link:"https://gs.dlut.edu.cn"},
 {school:"大连理工大学",lv:"985",major:"土木工程",type:"夏令营",title:"建设工程学部优秀大学生学术夏令营",time:"6月报名",req:"前25%",form:"学术报告+面试",link:"https://gs.dlut.edu.cn"},
 {school:"华中科技大学",lv:"985",major:"土木/工程管理",type:"预推免",title:"土木与水利工程学院预推免通知（含造价背景友好方向）",time:"9月中旬",req:"造价/管理背景可报工程管理，前20%",form:"综合面试+英语口语",link:"http://yzb.hust.edu.cn"},
 {school:"武汉大学",lv:"985",major:"土木/水利",type:"夏令营",title:"土木建筑工程学院暑期夏令营",time:"6月报名",req:"前20%，岩土与桥隧方向均招",form:"综合面试+英语口试",link:"https://gs.whu.edu.cn"},
 {school:"武汉大学",lv:"985",major:"经管类",type:"夏令营",title:"经济与管理学院夏令营（接受工科跨保）",time:"6月报名",req:"前20%，六级≥425",form:"笔试+无领导小组",link:"https://gs.whu.edu.cn"},
 {school:"中南大学",lv:"985",major:"土木/交通运输",type:"预推免",title:"土木工程学院预推免复试通知",time:"9月中旬",req:"推免资格+前20%，高铁桥梁方向招生较多",form:"结构力学笔试+英语听说+综合面试",link:"https://gra.csu.edu.cn"},
 {school:"湖南大学",lv:"985",major:"土木工程",type:"夏令营",title:"土木工程学院优秀大学生暑期学校",time:"6月报名，7月营期",req:"前20%，风工程与桥梁抗风方向特色",form:"学术讲座+分组面试",link:"http://gra.hnu.edu.cn"},
 {school:"重庆大学",lv:"985",major:"土木工程",type:"夏令营",title:"土木工程学院夏令营（山区桥梁与隧道国家重点实验室）",time:"6月报名",req:"前25%，山区桥梁方向特色鲜明",form:"实验室参观+导师双选+面试",link:"https://yz.cqu.edu.cn"},
 {school:"重庆大学",lv:"985",major:"工程管理",type:"预推免",title:"管理科学与房地产学院预推免（工程造价强相关）",time:"9月",req:"前20%，工程造价/管理背景高度匹配",form:"综合面试+英语",link:"https://yz.cqu.edu.cn"},
 {school:"西安交通大学",lv:"985",major:"土木/管理科学",type:"直博",title:"人居环境与建筑工程学院直博生招生",time:"9-10月",req:"科研经历优先，直博补助高",form:"申请-考核制",link:"https://yz.xjtu.edu.cn"},
 {school:"西北工业大学",lv:"985",major:"土木/交通",type:"预推免",title:"力学与土木建筑学院预推免通知",time:"9月中旬",req:"前25%，结构工程方向",form:"专业面试+英语",link:"https://yzb.nwpu.edu.cn"},
 {school:"华南理工大学",lv:"985",major:"土木水利",type:"夏令营",title:"土木与交通学院优秀大学生夏令营",time:"6月报名",req:"前20%，亚热带桥梁抗风抗震特色",form:"面试+英语口试",link:"http://yjszs.hust.edu.cn"},
 {school:"中山大学",lv:"985",major:"工程管理",type:"预推免",title:"土木工程学院接收推免生（智能建造与管理方向）",time:"9月",req:"前25%，工科背景",form:"综合面试",link:"https://graduate.sysu.edu.cn"},
 {school:"四川大学",lv:"985",major:"土木工程",type:"预推免",title:"建筑与环境学院土木方向预推免",time:"9月中旬",req:"前25%，岩土与桥隧均招",form:"面试+英语",link:"https://yz.scu.edu.cn"},
 {school:"电子科技大学",lv:"985",major:"经管类",type:"夏令营",title:"经济与管理学院夏令营（管理科学与工程）",time:"6月报名",req:"前20%，数学好，工科跨保友好",form:"笔试+面试",link:"https://yjsjy.uestc.edu.cn"},
 {school:"南开大学",lv:"985",major:"经管类",type:"预推免",title:"商学院接收推免生（工程管理/物流方向）",time:"9月",req:"前25%，经管/工科背景",form:"综合面试+英语",link:"https://yzb.nankai.edu.cn"},
 {school:"东北大学",lv:"985",major:"土木工程",type:"预推免",title:"资源与土木工程学院预推免通知",time:"9月",req:"前25%，结构/桥隧方向",form:"专业面试+英语",link:"https://yzb.neu.edu.cn"},
 {school:"吉林大学",lv:"985",major:"交通运输",type:"夏令营",title:"交通学院优秀大学生夏令营",time:"6月报名",req:"前25%，道路与桥梁方向",form:"学术营+面试",link:"http://yjsy.jlu.edu.cn"},
 {school:"山东大学",lv:"985",major:"土木/水利",type:"预推免",title:"土建与水利学院预推免（桥隧方向）",time:"9月",req:"前25%",form:"面试+英语口试",link:"https://www.yz.sdu.edu.cn"},
 {school:"厦门大学",lv:"985",major:"工程管理",type:"夏令营",title:"建筑与土木工程学院夏令营（含工程管理）",time:"6月报名",req:"前25%，工科背景",form:"面试+英语",link:"https://gs.xmu.edu.cn"},
 {school:"中国海洋大学",lv:"985",major:"土木工程",type:"预推免",title:"土木工程系预推免接收通知（海洋结构物特色）",time:"9月",req:"前30%",form:"专业面试",link:"https://grad.ouc.edu.cn"},
 {school:"北京航空航天大学",lv:"985",major:"交通运输",type:"夏令营",title:"交通科学与工程学院优秀大学生夏令营",time:"6月报名",req:"前20%，智能交通/空天结构方向",form:"笔试+面试",link:"https://yzb.buaa.edu.cn"},
 {school:"北京理工大学",lv:"985",major:"力学/土木",type:"预推免",title:"宇航/机电相关学院接收推免（结构力学方向）",time:"9月",req:"前20%",form:"综合面试+英语",link:"https://grd.bit.edu.cn"},
 {school:"北京师范大学",lv:"985",major:"经管类",type:"夏令营",title:"经济与工商管理学院夏令营（接受工科跨保）",time:"6月报名",req:"前20%",form:"笔试+面试",link:"https://yz.bnu.edu.cn"},
 {school:"华东师范大学",lv:"985",major:"经管类",type:"预推免",title:"经济与管理学部预推免（统计与工程管理）",time:"9月",req:"前25%",form:"面试+英语",link:"https://yjszs.ecnu.edu.cn"},
 {school:"西北农林科技大学",lv:"985",major:"工程管理",type:"预推免",title:"水利与建筑工程学院预推免（工程造价方向）",time:"9月",req:"前30%，工科背景",form:"专业面试",link:"https://yz.nwafu.edu.cn"},
 {school:"中央财经大学",lv:"211",major:"经管类",type:"预推免",title:"管理科学与工程学院预推免（工程造价背景契合）",time:"9月中旬",req:"推免资格，管科专业与造价背景高度匹配",form:"综合面试+英语听说测试",link:"https://gs.cufe.edu.cn"},
 {school:"上海财经大学",lv:"211",major:"经管类",type:"夏令营",title:"经济学院全国优秀大学生夏令营（跨专业欢迎）",time:"5-6月报名",req:"前15%，数学基础好，工科跨考友好",form:"笔试（数学+经济学）+面试",link:"https://gs.sufe.edu.cn"},
 {school:"中南财经政法大学",lv:"211",major:"经管类",type:"夏令营",title:"工商管理学院夏令营（接受工科跨保）",time:"6月报名",req:"前20%，六级≥425",form:"无领导小组+个面",link:"https://yjsy.zuel.edu.cn"},
 {school:"北京交通大学",lv:"211",major:"土木/交通运输",type:"夏令营",title:"土木建筑工程学院大学生夏令营",time:"6月中旬截止",req:"211以上或学科评估B+以上，前30%",form:"面试为主，含专业英语问答",link:"https://gs.bjtu.edu.cn"},
 {school:"北京交通大学",lv:"211",major:"桥梁与隧道",type:"导师动态",title:"桥梁工程系教授团队（轨道交通桥梁）招收推免生",time:"7-9月联系最佳",req:"桥梁/隧道方向，有结构设计经验优先",form:"邮件联系+线上面谈",link:"https://civil.bjtu.edu.cn"},
 {school:"武汉理工大学",lv:"211",major:"土木工程",type:"预推免",title:"土木工程与建筑学院预推免（桥梁与道路方向）",time:"9月",req:"前25%，材料复合桥面特色",form:"专业面试+英语",link:"http://yx.whut.edu.cn"},
 {school:"西南交通大学",lv:"211",major:"桥梁与隧道工程",type:"夏令营",title:"土木工程学院桥梁系夏令营（桥隧国家重点学科）",time:"6月初报名",req:"211及以上，前25%，桥隧方向强烈推荐",form:"专业笔试+面试，优秀营员直接预录取",link:"https://yz.swjtu.edu.cn"},
 {school:"西南交通大学",lv:"211",major:"桥梁与隧道",type:"导师动态",title:"桥梁智能监测团队招收对传感/无人机检测感兴趣的推免生",time:"7-9月联系最佳",req:"造价转桥隧背景可，需补结构力学",form:"邮件联系+线上面谈",link:"https://civil.swjtu.edu.cn"},
 {school:"西南交通大学",lv:"211",major:"交通运输工程",type:"预推免",title:"交通运输与物流学院预推免（含智能交通方向）",time:"9月上旬",req:"前25%，交通运输背景优先",form:"专业面试+英语自我介绍",link:"https://yz.swjtu.edu.cn"},
 // ===== 2025-2026 实时新增（基于 2026-07 检索）=====
 {school:"同济大学",lv:"985",major:"智能建造/土木",type:"暑期研学营",title:"国家卓越工程师学院 2026 年「暑期研学营」活动通知",time:"7月13-14日线下",req:"本科前15%（科研突出可放宽）",form:"材料审核+录取约 100 人·含智能建造等 18 个培养领域",link:"https://www.tongji.edu.cn"},
 {school:"中南大学",lv:"985",major:"土木/交通运输",type:"夏令营",title:"2026 年土木工程学院夏令营入营名单（已公布）",time:"7月开营",req:"前 20%，高铁桥梁方向招生较多",form:"结构力学笔试+英语听说+综合面试",link:"https://gra.csu.edu.cn"},
 {school:"湖南大学",lv:"985",major:"土木工程",type:"夏令营",title:"2026 年土木工程学院暑期学校·风工程与桥梁抗风方向",time:"6月报名·7月营期",req:"前20%",form:"学术讲座+分组面试+实验室参观",link:"http://gra.hnu.edu.cn"},
 {school:"重庆大学",lv:"985",major:"桥梁与隧道",type:"夏令营",title:"2026 土木工程学院夏令营（山区桥梁与隧道国家重点实验室）",time:"6月报名·7月开营",req:"前25%，山区桥梁方向特色",form:"实验室参观+导师双选+面试",link:"https://yz.cqu.edu.cn"},
 {school:"东南大学",lv:"985",major:"土木/桥隧",type:"导师动态",title:"桥梁系教授团队 2026 年招收对 AI 监测/数字孪生感兴趣的推免生 2-3 名",time:"常年接受邮件",req:"编程基础（Python/MATLAB）",form:"邮件简历+线上交流",link:"https://civil.seu.edu.cn"},
 {school:"哈尔滨工业大学",lv:"985",major:"桥梁与隧道",type:"预推免",title:"2026 土木工程学院桥隧方向预推免·寒区桥梁特色",time:"9月",req:"推免资格，前 20%",form:"专业面试+文献翻译",link:"http://yzb.hit.edu.cn"},
 {school:"北京交通大学",lv:"211",major:"桥梁与隧道",type:"导师动态",title:"2026 桥梁工程系教授团队（轨道交通桥梁）招收推免生",time:"7-9月联系最佳",req:"桥梁/隧道方向，有结构设计经验优先",form:"邮件联系+线上面谈",link:"https://civil.bjtu.edu.cn"}
];
