// ===== 单词库 · 第二部分 =====
window.DB.words = window.DB.words.concat([
 {en:"rehabilitation",cn:"n. 修复；加固改造",s:"The old bridge underwent rehabilitation.",sc:"老桥进行了加固改造。"},
 {en:"monitoring",cn:"n. 监测",s:"Structural health monitoring runs in real time.",sc:"结构健康监测实时运行。"},
 {en:"sensor",cn:"n. 传感器",s:"Sensors record strain and temperature.",sc:"传感器记录应变与温度。"},
 {en:"tunnel",cn:"n. 隧道",s:"The tunnel passes under the strait.",sc:"隧道从海峡下方穿过。"},
 {en:"excavation",cn:"n. 开挖",s:"Excavation reached the design depth.",sc:"开挖达到设计深度。"},
 {en:"geotechnical",cn:"adj. 岩土的",s:"Geotechnical investigation came first.",sc:"岩土勘察先行。"},
 {en:"soil",cn:"n. 土；土壤",s:"Soft soil requires pile foundations.",sc:"软土需要采用桩基础。"},
 {en:"bedrock",cn:"n. 基岩",s:"The piles are socketed into bedrock.",sc:"桩嵌入基岩。"},
 {en:"settlement",cn:"n. 沉降",s:"Uneven settlement damages the structure.",sc:"不均匀沉降会损坏结构。"},
 {en:"slope",cn:"n. 边坡；坡度",s:"The slope was stabilized with anchors.",sc:"边坡用锚杆加固。"},
 {en:"drainage",cn:"n. 排水",s:"Good drainage prevents deterioration.",sc:"良好排水可防止劣化。"},
 {en:"asphalt",cn:"n. 沥青",s:"The deck was paved with asphalt concrete.",sc:"桥面铺筑沥青混凝土。"},
 {en:"steel",cn:"n. 钢材",s:"High-strength steel reduces self-weight.",sc:"高强钢可减轻自重。"},
 {en:"weld",cn:"v./n. 焊接；焊缝",s:"All welds were tested by ultrasound.",sc:"所有焊缝均经超声检测。"},
 {en:"bolt",cn:"n. 螺栓",s:"High-strength bolts join the plates.",sc:"高强螺栓连接钢板。"},
 {en:"tension",cn:"n. 拉力；张拉",s:"The cable is under high tension.",sc:"缆索承受很大拉力。"},
 {en:"compression",cn:"n. 压力；受压",s:"Arches work mainly in compression.",sc:"拱主要受压工作。"},
 {en:"torsion",cn:"n. 扭转",s:"Curved bridges suffer torsion.",sc:"曲线桥会产生扭转。"},
 {en:"buckling",cn:"n. 屈曲；失稳",s:"Slender columns may fail by buckling.",sc:"细长柱可能因屈曲破坏。"},
 {en:"stiffness",cn:"n. 刚度",s:"Greater stiffness means less deflection.",sc:"刚度越大，挠度越小。"},
 {en:"stability",cn:"n. 稳定性",s:"Overall stability was checked.",sc:"整体稳定性已验算。"},
 {en:"dynamic",cn:"adj. 动力的",s:"Dynamic analysis covers earthquakes.",sc:"动力分析涵盖地震作用。"},
 {en:"static",cn:"adj. 静力的",s:"Static tests preceded opening.",sc:"通车前进行了静载试验。"},
 {en:"finite element",cn:"n. 有限元",s:"A finite element model was built.",sc:"建立了有限元模型。"},
 {en:"simulation",cn:"n. 仿真；模拟",s:"Numerical simulation guided the design.",sc:"数值模拟指导设计。"},
 {en:"digital twin",cn:"n. 数字孪生",s:"A digital twin mirrors the real bridge.",sc:"数字孪生镜像真实桥梁。"},
 {en:"BIM",cn:"n. 建筑信息模型",s:"BIM improves design coordination.",sc:"BIM提升设计协同效率。"},
 {en:"sustainable",cn:"adj. 可持续的",s:"Sustainable materials cut carbon.",sc:"可持续材料降低碳排放。"},
 {en:"infrastructure",cn:"n. 基础设施",s:"Bridges are key infrastructure.",sc:"桥梁是关键基础设施。"},
 {en:"highway",cn:"n. 公路；高速公路",s:"The highway crosses three rivers.",sc:"这条高速跨越三条河。"},
 {en:"railway",cn:"n. 铁路",s:"High-speed railway bridges demand strict deflection limits.",sc:"高铁桥对挠度限制极严。"},
 {en:"navigation",cn:"n. 通航",s:"Navigation clearance is 50 meters.",sc:"通航净空为50米。"},
 {en:"clearance",cn:"n. 净空",s:"Vertical clearance limits the design.",sc:"竖向净空制约设计。"},
 {en:"girder erection",cn:"n. 架梁",s:"Girder erection used a launching gantry.",sc:"采用架桥机架梁。"},
 {en:"closure",cn:"n. 合龙",s:"The final closure was completed at dawn.",sc:"最终合龙在黎明完成。"},
 {en:"deterioration",cn:"n. 劣化；退化",s:"Deterioration accelerates without repair.",sc:"不维修会加速劣化。"},
 {en:"crack",cn:"n. 裂缝",s:"Hairline cracks are under observation.",sc:"细微裂缝处于观察中。"},
 {en:"reliability",cn:"n. 可靠度",s:"Reliability theory underpins the code.",sc:"可靠度理论是规范的基础。"},
 {en:"risk assessment",cn:"n. 风险评估",s:"Risk assessment guides maintenance funds.",sc:"风险评估指导养护资金分配。"},
 {en:"life cycle",cn:"n. 全寿命周期",s:"Life-cycle cost matters more than first cost.",sc:"全寿命成本比初期造价更重要。"},
 {en:"contractor",cn:"n. 承包商",s:"The contractor mobilized in March.",sc:"承包商三月进场。"},
 {en:"consultant",cn:"n. 咨询工程师",s:"The consultant reviewed the drawings.",sc:"咨询工程师审查了图纸。"},
 {en:"schedule",cn:"n. 进度计划",s:"The schedule allows 36 months.",sc:"工期计划为36个月。"},
 {en:"quality control",cn:"n. 质量控制",s:"Quality control covers every batch of concrete.",sc:"每批混凝土都要质量控制。"},
 {en:"safety",cn:"n. 安全",s:"Safety is the top priority on site.",sc:"安全是工地第一要务。"},
 {en:"hydration",cn:"n. 水化",s:"Cement hydration releases heat.",sc:"水泥水化会放热。"},
 {en:"admixture",cn:"n. 外加剂",s:"Admixtures improve workability.",sc:"外加剂改善和易性。"},
 {en:"aggregate",cn:"n. 骨料",s:"Aggregates make up most of concrete.",sc:"骨料占混凝土的大部分。"},
 {en:"modulus of elasticity",cn:"n. 弹性模量",s:"Steel has a high modulus of elasticity.",sc:"钢材弹性模量很高。"},
 {en:"resilience",cn:"n. 韧性；恢复力",s:"Resilient design speeds post-quake recovery.",sc:"韧性设计加快震后恢复。"}
]);
