// ===== SCI风格英文短文库（每日5篇轮换 · 含翻译与阅读题）=====
window.DB.readings = [
 {title:"Structural Health Monitoring of Long-Span Bridges",src:"Engineering Structures (style)",
  en:"Structural health monitoring (SHM) systems have become essential for long-span bridges. By installing sensors such as accelerometers, strain gauges, and GPS receivers, engineers can track the real-time behavior of a bridge under traffic and wind loads. The collected data help identify abnormal responses at an early stage, so that maintenance can be scheduled before minor damage develops into serious deterioration. Recent studies show that combining SHM data with machine learning greatly improves the accuracy of damage detection.",
  cn:"结构健康监测（SHM）系统已成为大跨桥梁不可或缺的部分。通过安装加速度计、应变片和GPS接收器等传感器，工程师可以实时跟踪桥梁在车辆与风荷载作用下的行为。所采集的数据有助于在早期发现异常响应，从而在轻微损伤发展为严重劣化之前安排养护。近期研究表明，将监测数据与机器学习结合能显著提高损伤识别的准确性。",
  q:"What is the main benefit of SHM mentioned in the passage?",
  opts:["It reduces construction cost directly","It detects abnormal behavior early for timely maintenance","It replaces all manual inspections completely","It increases the bridge span"],a:1},
 {title:"Fatigue Behavior of Orthotropic Steel Decks",src:"Journal of Bridge Engineering (style)",
  en:"Orthotropic steel decks are widely used in long-span bridges because of their light weight and high strength. However, repeated wheel loads cause fatigue cracks at welded joints, especially at rib-to-deck connections. Researchers have proposed several countermeasures, including thicker deck plates, improved weld details, and ultra-high performance concrete (UHPC) overlays. Field applications indicate that a UHPC layer can significantly reduce local stress ranges and extend fatigue life.",
  cn:"正交异性钢桥面板因自重轻、强度高而广泛应用于大跨桥梁。然而，反复的车轮荷载会在焊接接头处（尤其是纵肋与面板连接处）引起疲劳裂缝。研究者提出了多种对策，包括加厚面板、改进焊接细节以及铺设超高性能混凝土（UHPC）层。工程应用表明，UHPC层能显著降低局部应力幅并延长疲劳寿命。",
  q:"Which measure is said to reduce local stress ranges?",
  opts:["Using lighter vehicles","UHPC overlay on the deck","Removing welded joints","Shortening the span"],a:1},
 {title:"Seismic Isolation for Bridge Design",src:"Earthquake Engineering (style)",
  en:"Seismic isolation is an effective strategy to protect bridges in earthquake-prone regions. Isolation bearings, such as lead-rubber bearings and friction pendulum systems, lengthen the natural period of the structure and dissipate seismic energy. As a result, the forces transmitted to piers and foundations are greatly reduced. Compared with conventional ductility design, isolated bridges usually suffer less damage and can be reopened to traffic soon after a strong earthquake.",
  cn:"隔震是保护地震多发区桥梁的有效策略。铅芯橡胶支座、摩擦摆系统等隔震支座能延长结构自振周期并耗散地震能量，从而大幅降低传递到桥墩和基础的地震力。与传统延性设计相比，隔震桥梁震后损伤通常更轻，可在强震后较快恢复通车。",
  q:"How do isolation bearings protect bridges?",
  opts:["By making piers stiffer","By lengthening the period and dissipating energy","By adding more piers","By reducing traffic volume"],a:1},
 {title:"Digital Twins in Bridge Management",src:"Automation in Construction (style)",
  en:"A digital twin is a virtual model that mirrors a physical bridge throughout its life cycle. By integrating BIM models, sensor data, and inspection records, the digital twin updates itself continuously and predicts future performance. Bridge owners can simulate different maintenance strategies in the virtual space before applying them in reality, which reduces cost and avoids unnecessary interventions. Digital twins are regarded as a core technology of smart infrastructure.",
  cn:"数字孪生是与实体桥梁全寿命周期相互映射的虚拟模型。通过集成BIM模型、传感器数据和检测记录，数字孪生持续自我更新并预测未来性能。桥梁管理者可先在虚拟空间中模拟不同养护策略，再应用于现实，从而降低成本、避免不必要的干预。数字孪生被视为智慧基础设施的核心技术。",
  q:"What can owners do with a digital twin before real maintenance?",
  opts:["Rebuild the bridge","Simulate strategies virtually","Cancel all inspections","Increase traffic load"],a:1},
 {title:"UHPC: A Material for Next-Generation Bridges",src:"Cement and Concrete Research (style)",
  en:"Ultra-high performance concrete (UHPC) exhibits compressive strength above 120 MPa and excellent durability. Its dense microstructure prevents the ingress of chloride ions, making it ideal for marine bridges. Although the initial cost of UHPC is higher than normal concrete, thinner sections and longer service life often lead to lower life-cycle costs. UHPC has been successfully applied in bridge joints, deck overlays, and even full precast girders.",
  cn:"超高性能混凝土（UHPC）抗压强度超过120MPa，耐久性优异。其致密的微观结构能阻止氯离子侵入，非常适合海洋环境桥梁。虽然UHPC初期成本高于普通混凝土，但更薄的截面和更长的寿命往往带来更低的全寿命成本。UHPC已成功应用于桥梁接缝、桥面铺装层乃至整体预制梁。",
  q:"Why is UHPC suitable for marine bridges?",
  opts:["It is the cheapest material","Its dense structure resists chloride ingress","It is lighter than water","It needs no design"],a:1},
 {title:"Wind-Induced Vibration of Long-Span Bridges",src:"J. of Wind Engineering (style)",
  en:"As spans become longer, bridges grow more sensitive to wind. Flutter is a dangerous self-excited vibration that can lead to collapse, as shown by the Tacoma Narrows Bridge in 1940. Vortex-induced vibration, though less destructive, affects driving comfort and fatigue life. Wind tunnel tests and computational fluid dynamics are used together to verify aerodynamic stability, and countermeasures such as fairings and central slots are often adopted.",
  cn:"随着跨径增大，桥梁对风越来越敏感。颤振是一种危险的自激振动，可能导致垮塌——1940年塔科马海峡桥即为例证。涡激振动虽破坏性较小，但影响行车舒适性与疲劳寿命。风洞试验与计算流体力学被联合用于验证气动稳定性，并常采用导流板、中央开槽等对策。",
  q:"Which vibration type is described as potentially causing collapse?",
  opts:["Vortex-induced vibration","Flutter","Traffic vibration","Thermal movement"],a:1},
 {title:"Life-Cycle Cost Analysis in Bridge Engineering",src:"Structure & Infrastructure Eng. (style)",
  en:"Decisions based only on initial construction cost often prove uneconomical. Life-cycle cost analysis (LCCA) considers construction, inspection, maintenance, repair, and even user costs caused by traffic closures. For example, a corrosion-resistant material with a higher first cost may save millions over a century of service. Many agencies now require LCCA in the tender evaluation of major bridges, pushing the industry toward long-term thinking.",
  cn:"仅依据初期建造成本做决策往往并不经济。全寿命周期成本分析（LCCA）综合考虑建造、检测、养护、维修，甚至封闭交通带来的用户成本。例如，初期较贵的耐腐蚀材料，在百年服役期内可能节省数百万元。许多机构已要求在大桥招标评审中进行LCCA，推动行业转向长期思维。",
  q:"What does LCCA include besides construction cost?",
  opts:["Only material price","Inspection, maintenance, repair and user costs","Designer salaries only","Advertisement fees"],a:1},
 {title:"Accelerated Bridge Construction (ABC)",src:"J. of Construction Eng. (style)",
  en:"Accelerated bridge construction uses prefabricated elements and rapid installation techniques to minimize traffic disruption. Entire spans can be built off-site and moved into place overnight using self-propelled modular transporters. ABC improves work-zone safety and construction quality, since most components are produced in controlled factory environments. The method is especially valuable for replacing aging bridges on busy urban corridors.",
  cn:"快速桥梁建造（ABC）利用预制构件和快速安装技术，把交通干扰降到最低。整跨桥梁可在场外建好，借助自行式模块运输车连夜就位。由于大部分构件在受控的工厂环境中生产，ABC提升了作业区安全性与施工质量。该方法对更换繁忙城市走廊上的老龄桥梁尤其有价值。",
  q:"Why does ABC improve construction quality?",
  opts:["Workers are faster at night","Components are made in controlled factories","Bridges become shorter","No design is needed"],a:1}
];

